server {
    listen 80;
    server_name localhost;

    location /static/ {
        alias /usr/src/app/staticfiles/;
        autoindex on; # Helpful for debugging
        expires 1d; # Cache static files for 1 day
    }
}