# Generated by Django 6.0.2 on 2026-03-04 15:10

from django.db import migrations
import datetime
import os
from django.db import migrations
from django.utils import timezone
from django.conf import settings


def create_initial_data(apps, schema_editor):
    """Create initial users, Component, Function, and Project data."""
    # Allow projects to opt-out of this data migration
    if not getattr(settings, "RUN_CORE_INITIAL_DATA_MIGRATION", False):
        return

    User = apps.get_model("auth", "User")
    CategoryModel = apps.get_model("specification_centralized_core", "CategoryModel")
    ComponentModel = apps.get_model("specification_centralized_core", "ComponentModel")
    ComplexityModel = apps.get_model(
        "specification_centralized_core", "ComplexityModel"
    )
    FunctionModel = apps.get_model("specification_centralized_core", "FunctionModel")
    ProcessModel = apps.get_model("specification_centralized_core", "ProcessModel")
    PriorityModel = apps.get_model("specification_centralized_core", "PriorityModel")
    ProjectModel = apps.get_model("specification_centralized_core", "ProjectModel")
    ProjectMilestoneModel = apps.get_model(
        "specification_centralized_core", "ProjectMilestoneModel"
    )
    UserSettingModel = apps.get_model(
        "specification_centralized_core", "UserSettingModel"
    )
    ProjectSettingModel = apps.get_model(
        "specification_centralized_core", "ProjectSettingModel"
    )
    SpecificationImportTypeModel = apps.get_model(
        "specification_centralized_core", "SpecificationImportTypeModel"
    )

    # 1. Create Users
    username = os.environ.get("DJANGO_SUPERUSER_USERNAME", "admin")
    email = os.environ.get("DJANGO_SUPERUSER_EMAIL", "admin@example.com")
    password = os.environ.get("DJANGO_SUPERUSER_PASSWORD", "admin")

    # Create "admin" is a supperuser
    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(username=username, email=email, password=password)

    user1_username = os.environ.get("DJANGO_USER1_USERNAME", "user1")
    user1_email = os.environ.get("DJANGO_USER1_EMAIL", "user1@example.com")
    user1_password = os.environ.get("DJANGO_USER1_PASSWORD", "user1")
    if not User.objects.filter(username=user1_username).exists():
        User.objects.create_user(
            username=user1_username,
            email=user1_email,
            password=user1_password,
            is_superuser=True,
        )

    user2_username = os.environ.get("DJANGO_USER2_USERNAME", "user2")
    user2_email = os.environ.get("DJANGO_USER2_EMAIL", "user2@example.com")
    user2_password = os.environ.get("DJANGO_USER2_PASSWORD", "user2")
    if not User.objects.filter(username=user2_username).exists():
        User.objects.create_user(
            username=user2_username,
            email=user2_email,
            password=user2_password,
            is_superuser=True,
        )

    # 2. Create Project
    # Retrieve the admin user to assign as owner
    username = os.environ.get("DJANGO_SUPERUSER_USERNAME", "admin")
    owner = User.objects.filter(username=username).first()

    # Fallback to any user if admin specific username is not found
    if not owner:
        owner = User.objects.first()

    project = None
    if owner:
        project_data = {
            "code": "PROJ-001",
            "name": "Test Project",
            "description": "This is the test project created by migration.",
            "owner_user": owner,
        }
        project = ProjectModel.objects.filter(code=project_data["code"]).first()
        if not project:
            project = ProjectModel.objects.create(**project_data)

    # 3. Create Components
    components = [
        {
            "code": "Uncategorized",
            "name": "Uncategorized",
            "type": "SWC",
            "description": "Uncategorized",
        },
        {
            "code": "LK",
            "name": "LaneKeeping",
            "type": "SWC",
            "description": "LaneKeeping",
        },
        {
            "code": "VF",
            "name": "VehicleFollowing",
            "type": "SWC",
            "description": "VehicleFollowing",
        },
        {
            "code": "LCA",
            "name": "LaneChangeAssist",
            "type": "SWC",
            "description": "LaneChangeAssist",
        },
        {
            "code": "360degPerception",
            "name": "360degPerception",
            "type": "SWC",
            "description": "360degPerception",
        },
        {
            "code": "LLL",
            "name": "LaneLevelLocalization",
            "type": "SWC",
            "description": "LaneLevelLocalization",
        },
        {
            "code": "MF",
            "name": "MapFusion",
            "type": "SWC",
            "description": "MapFusion",
        },
        {
            "code": "LaMP",
            "name": "LateralMotionPlanner",
            "type": "SWC",
            "description": "LateralMotionPlanner",
        },
        {
            "code": "LaDSC",
            "name": "LateralDrivingStateChecker",
            "type": "SWC",
            "description": "LateralDrivingStateChecker",
        },
        {
            "code": "LaCM",
            "name": "LateralControllerMain",
            "type": "SWC",
            "description": "LateralControllerMain",
        },
        {
            "code": "LoMP",
            "name": "LongitudinalMotionPlanner",
            "type": "SWC",
            "description": "LongitudinalMotionPlanner",
        },
        {
            "code": "BC",
            "name": "BehaviorContext",
            "type": "SWC",
            "description": "BehaviorContext",
        },
        {
            "code": "RedTpM/RedTps",
            "name": "RedundantTrajectoryPlanner",
            "type": "SWC",
            "description": "RedundantTrajectoryPlanner",
        },
        {
            "code": "TC",
            "name": "TrajectoryChecker",
            "type": "SWC",
            "description": "TrajectoryChecker",
        },
        {
            "code": "ExternalCameraPerception",
            "name": "ExternalCameraPerception",
            "type": "SWCG",
            "description": "ExternalCameraPerception",
        },
        {
            "code": "SonarRecognition",
            "name": "SonarRecognition",
            "type": "SWCG",
            "description": "SonarRecognition",
        },
        {
            "code": "ThreeSixtyDegreePerception",
            "name": "ThreeSixtyDegreePerception",
            "type": "SWCG",
            "description": "ThreeSixtyDegreePerception",
        },
        {
            "code": "FcmPmdAdaptor",
            "name": "FcmPmdAdaptor",
            "type": "SWCG",
            "description": "FcmPmdAdaptor",
        },
        {
            "code": "DriverMonitoringSystem",
            "name": "DriverMonitoringSystem",
            "type": "SWCG",
            "description": "DriverMonitoringSystem",
        },
        {
            "code": "LowSpeedEgoMotionPerception",
            "name": "LowSpeedEgoMotionPerception",
            "type": "SWCG",
            "description": "LowSpeedEgoMotionPerception",
        },
        {
            "code": "AllSpeedEgoMotionPerception",
            "name": "AllSpeedEgoMotionPerception",
            "type": "SWCG",
            "description": "AllSpeedEgoMotionPerception",
        },
        {
            "code": "EgoMotionPerceptionVerification",
            "name": "EgoMotionPerceptionVerification",
            "type": "SWCG",
            "description": "EgoMotionPerceptionVerification",
        },
        {
            "code": "ObjectFusion",
            "name": "ObjectFusion",
            "type": "SWCG",
            "description": "ObjectFusion",
        },
        {
            "code": "RoadFusion",
            "name": "RoadFusion",
            "type": "SWCG",
            "description": "RoadFusion",
        },
        {
            "code": "AdvancedParkFusion",
            "name": "AdvancedParkFusion",
            "type": "SWCG",
            "description": "AdvancedParkFusion",
        },
        {
            "code": "IntersectionFusion",
            "name": "IntersectionFusion",
            "type": "SWCG",
            "description": "IntersectionFusion",
        },
        {
            "code": "RoadSignAssist (ExternalPerceptionFusion)",
            "name": "RoadSignAssist (ExternalPerceptionFusion)",
            "type": "SWCG",
            "description": "RoadSignAssist (ExternalPerceptionFusion)",
        },
        # {
        #     "code": "MapFusion",
        #     "name": "MapFusion",
        #     "type": "SWCG",
        #     "description": "MapFusion",
        # },
        {
            "code": "RoadClassificationJudgement",
            "name": "RoadClassificationJudgement",
            "type": "SWCG",
            "description": "RoadClassificationJudgement",
        },
        {
            "code": "TrailerCharacteristics",
            "name": "TrailerCharacteristics",
            "type": "SWCG",
            "description": "TrailerCharacteristics",
        },
        {
            "code": "MapServiceVehicle",
            "name": "MapServiceVehicle",
            "type": "SWCG",
            "description": "MapServiceVehicle",
        },
        {
            "code": "MapPdCollectionVehicle",
            "name": "MapPdCollectionVehicle",
            "type": "SWCG",
            "description": "MapPdCollectionVehicle",
        },
        {
            "code": "RoadlevelLocalization",
            "name": "RoadlevelLocalization",
            "type": "SWCG",
            "description": "RoadlevelLocalization",
        },
        # {
        #     "code": "LaneLevelLocalization",
        #     "name": "LaneLevelLocalization",
        #     "type": "SWCG",
        #     "description": "LaneLevelLocalization",
        # },
        {
            "code": "ParkingSystemApplicationMid",
            "name": "ParkingSystemApplicationMid",
            "type": "SWCG",
            "description": "ParkingSystemApplicationMid",
        },
        {
            "code": "SpeedPlanner",
            "name": "SpeedPlanner",
            "type": "SWCG",
            "description": "SpeedPlanner",
        },
        # {
        #     "code": "LaneChangeAssist",
        #     "name": "LaneChangeAssist",
        #     "type": "SWCG",
        #     "description": "LaneChangeAssist",
        # },
        {
            "code": "LaneTraceAssistLaneDepartureAlert",
            "name": "LaneTraceAssistLaneDepartureAlert",
            "type": "SWCG",
            "description": "LaneTraceAssistLaneDepartureAlert",
        },
        {
            "code": "EmergencyDrivingStopSystem",
            "name": "EmergencyDrivingStopSystem",
            "type": "SWCG",
            "description": "EmergencyDrivingStopSystem",
        },
        {
            "code": "RoadSignAssist (ChauffeurPlanner)",
            "name": "RoadSignAssist (ChauffeurPlanner)",
            "type": "SWCG",
            "description": "RoadSignAssist (ChauffeurPlanner)",
        },
        {
            "code": "AdvancedPark",
            "name": "AdvancedPark",
            "type": "SWCG",
            "description": "AdvancedPark",
        },
        {
            "code": "SmartDriveGuide",
            "name": "SmartDriveGuide",
            "type": "SWCG",
            "description": "SmartDriveGuide",
        },
        {
            "code": "TrailerBackupGuide",
            "name": "TrailerBackupGuide",
            "type": "SWCG",
            "description": "TrailerBackupGuide",
        },
        {
            "code": "PreCrashSafety",
            "name": "PreCrashSafety",
            "type": "SWCG",
            "description": "PreCrashSafety",
        },
        {
            "code": "ObstacleAnticipateAssist",
            "name": "ObstacleAnticipateAssist",
            "type": "SWCG",
            "description": "ObstacleAnticipateAssist",
        },
        {
            "code": "ParkingSupportBrake",
            "name": "ParkingSupportBrake",
            "type": "SWCG",
            "description": "ParkingSupportBrake",
        },
        {
            "code": "SurroundRadarApplications",
            "name": "SurroundRadarApplications",
            "type": "SWCG",
            "description": "SurroundRadarApplications",
        },
        {
            "code": "TrailerHandsOff",
            "name": "TrailerHandsOff",
            "type": "SWCG",
            "description": "TrailerHandsOff",
        },
        {
            "code": "GuardianJudgement",
            "name": "GuardianJudgement",
            "type": "SWCG",
            "description": "GuardianJudgement",
        },
        {
            "code": "GuardianFusion",
            "name": "GuardianFusion",
            "type": "SWCG",
            "description": "GuardianFusion",
        },
        {
            "code": "TrailerCollisionWarning",
            "name": "TrailerCollisionWarning",
            "type": "SWCG",
            "description": "TrailerCollisionWarning",
        },
        # {
        #     "code": "BehaviorContext",
        #     "name": "BehaviorContext",
        #     "type": "SWCG",
        #     "description": "BehaviorContext",
        # },
        {
            "code": "ADStateManager",
            "name": "ADStateManager",
            "type": "SWCG",
            "description": "ADStateManager",
        },
        # {
        #     "code": "TrajectoryChecker",
        #     "name": "TrajectoryChecker",
        #     "type": "SWCG",
        #     "description": "TrajectoryChecker",
        # },
        {
            "code": "LCAChecker",
            "name": "LCAChecker",
            "type": "SWCG",
            "description": "LCAChecker",
        },
        {
            "code": "RedundantTrajectoryPlannerMain",
            "name": "RedundantTrajectoryPlannerMain",
            "type": "SWCG",
            "description": "RedundantTrajectoryPlannerMain",
        },
        {
            "code": "RedundantTrajectoryPlannerSub",
            "name": "RedundantTrajectoryPlannerSub",
            "type": "SWCG",
            "description": "RedundantTrajectoryPlannerSub",
        },
        {
            "code": "MotionPlanner",
            "name": "MotionPlanner",
            "type": "SWCG",
            "description": "MotionPlanner",
        },
        # {
        #     "code": "LongitudinalMotionPlanner",
        #     "name": "LongitudinalMotionPlanner",
        #     "type": "SWCG",
        #     "description": "LongitudinalMotionPlanner",
        # },
        # {
        #     "code": "LateralDrivingStateChecker",
        #     "name": "LateralDrivingStateChecker",
        #     "type": "SWCG",
        #     "description": "LateralDrivingStateChecker",
        # },
        {
            "code": "InterCommBev",
            "name": "InterCommBev",
            "type": "SWCG",
            "description": "InterCommBev",
        },
        {
            "code": "HumanSystemIntegration",
            "name": "HumanSystemIntegration",
            "type": "SWCG",
            "description": "HumanSystemIntegration",
        },
        {
            "code": "ViewMonitor",
            "name": "ViewMonitor",
            "type": "SWCG",
            "description": "ViewMonitor",
        },
        {
            "code": "ExteriorLightingControl",
            "name": "ExteriorLightingControl",
            "type": "SWCG",
            "description": "ExteriorLightingControl",
        },
        {
            "code": "ADASLearningPackage",
            "name": "ADASLearningPackage",
            "type": "SWCG",
            "description": "ADASLearningPackage",
        },
        {
            "code": "ParkingApplicationArbitration",
            "name": "ParkingApplicationArbitration",
            "type": "SWCG",
            "description": "ParkingApplicationArbitration",
        },
        {
            "code": "LateralMotionControlArbitration",
            "name": "LateralMotionControlArbitration",
            "type": "SWCG",
            "description": "LateralMotionControlArbitration",
        },
        # {
        #     "code": "LateralControllerMain",
        #     "name": "LateralControllerMain",
        #     "type": "SWCG",
        #     "description": "LateralControllerMain",
        # },
        {
            "code": "LateralControllerSub",
            "name": "LateralControllerSub",
            "type": "SWCG",
            "description": "LateralControllerSub",
        },
        {
            "code": "LateralMotionControl",
            "name": "LateralMotionControl",
            "type": "SWCG",
            "description": "LateralMotionControl",
        },
        {
            "code": "FailureManager",
            "name": "FailureManager",
            "type": "SWCG",
            "description": "FailureManager",
        },
        {
            "code": "IOLayer",
            "name": "IOLayer",
            "type": "SWCG",
            "description": "IOLayer",
        },
        {
            "code": "MarketDataCollection",
            "name": "MarketDataCollection",
            "type": "SWCG",
            "description": "MarketDataCollection",
        },
        {
            "code": "DestinationJudge",
            "name": "DestinationJudge",
            "type": "SWCG",
            "description": "DestinationJudge",
        },
        {
            "code": "DriveRecorder",
            "name": "DriveRecorder",
            "type": "SWCG",
            "description": "DriveRecorder",
        },
        {
            "code": "NodeKicker",
            "name": "NodeKicker",
            "type": "SWCG",
            "description": "NodeKicker",
        },
    ]

    for comp in components:
        if not ComponentModel.objects.filter(code=comp["code"]).exists():
            ComponentModel.objects.create(project=project, **comp)

    # 4. Create Functions
    functions = [
        {
            "code": "FUNC-ACC",
            "name": "Acceleration",
            "type": "Performance",
            "description": "Vehicle acceleration capability",
        },
        {
            "code": "FUNC-BRK",
            "name": "Braking",
            "type": "Safety",
            "description": "Vehicle braking capability",
        },
        {
            "code": "FUNC-ENT",
            "name": "Entertainment",
            "type": "UX",
            "description": "Audio and Video playback",
        },
    ]

    for func in functions:
        if not FunctionModel.objects.filter(code=func["code"]).exists():
            FunctionModel.objects.create(project=project, **func)

    # 5. Create Processes
    processes = [
        {
            "code": "PI",
            "name": "Project Initiation",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "PMC",
            "name": "Project Monitor and Control",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "QA",
            "name": "Quality Assurance",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "CM",
            "name": "Configuration Management",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "PRM",
            "name": "Prolem Resolution Management",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "CRM",
            "name": "Change Request Management",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "SPM",
            "name": "Software Procurement/Supply Management",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "RW",
            "name": "Review Work Products",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "URD",
            "name": "User Requirement Definition",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "SYRD",
            "name": "System Requirement Definition",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "SYAD",
            "name": "System Architecture Design",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "SWRD",
            "name": "Software Requirement Definition",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "SWAD",
            "name": "Software Architecture Design",
            "type": "Core Process",
            "description": "",
        },
        {
            "code": "SCRD",
            "name": "Software Component Requirement Definition",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SCAD",
            "name": "Software Component Architecture Design",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SUD",
            "name": "Software Unit Design",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SUI",
            "name": "Software Unit Implementation",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SUT",
            "name": "Software Unit Test",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SCIT",
            "name": "Software Component Integration Test",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SCQT",
            "name": "Software Component Quality Test",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SWIT",
            "name": "Software Integration Test",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SWQT",
            "name": "Software Qualification Test",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SYIT",
            "name": "System Integration Test",
            "type": "Software Component Development",
            "description": "",
        },
        {
            "code": "SYQT",
            "name": "System Qualification Test",
            "type": "Software Component Development",
            "description": "",
        },
    ]

    for proc in processes:
        if not ProcessModel.objects.filter(code=proc["code"]).exists():
            ProcessModel.objects.create(project=project, **proc)

    # 6. Create Priorities
    priorities = [
        {
            "code": "PRIO-HIGH",
            "name": "High",
            "type": "Default",
            "description": "High priority",
        },
        {
            "code": "PRIO-MED",
            "name": "Medium",
            "type": "Default",
            "description": "Medium priority",
        },
        {
            "code": "PRIO-LOW",
            "name": "Low",
            "type": "Default",
            "description": "Low priority",
        },
    ]

    for prio in priorities:
        if not PriorityModel.objects.filter(code=prio["code"]).exists():
            PriorityModel.objects.create(project=project, **prio)

    # 7. Create Complexities
    complexities = [
        {
            "code": "CPLX-VHARD",
            "name": "Very Hard",
            "type": "Default",
            "description": "High complexity",
        },
        {
            "code": "CPLX-HARD",
            "name": "Hard",
            "type": "Default",
            "description": "High complexity",
        },
        {
            "code": "CPLX-MED",
            "name": "Medium",
            "type": "Default",
            "description": "Medium complexity",
        },
        {
            "code": "CPLX-EASY",
            "name": "Easy",
            "type": "Default",
            "description": "Low complexity",
        },
    ]

    for cplx in complexities:
        if not ComplexityModel.objects.filter(code=cplx["code"]).exists():
            ComplexityModel.objects.create(project=project, **cplx)

    # 8. Create Project Milestones
    if project:
        base_date = timezone.now()
        milestones = [
            {
                "name": "Milestone 1",
                "description": "Milestone 1",
                "start_date": base_date,
                "end_date": base_date + datetime.timedelta(days=14),
            },
            {
                "name": "Milestone 2",
                "description": "Milestone 2",
                "start_date": base_date + datetime.timedelta(days=15),
                "end_date": base_date + datetime.timedelta(days=30),
            },
            {
                "name": "Milestone 3",
                "description": "Milestone 3",
                "start_date": base_date + datetime.timedelta(days=31),
                "end_date": base_date + datetime.timedelta(days=60),
            },
            {
                "name": "Milestone 4",
                "description": "Milestone 4",
                "start_date": base_date + datetime.timedelta(days=61),
                "end_date": base_date + datetime.timedelta(days=75),
            },
            {
                "name": "Milestone 5",
                "description": "Milestone 5",
                "start_date": base_date + datetime.timedelta(days=76),
                "end_date": base_date + datetime.timedelta(days=80),
            },
        ]

        for ms in milestones:
            if not ProjectMilestoneModel.objects.filter(
                project=project, name=ms["name"]
            ).exists():
                ProjectMilestoneModel.objects.create(project=project, **ms)

    # 9. Create Categories
    categories = [
        {"code": "CAT-FUNC", "name": "Functional"},
        {"code": "CAT-NON-FUNC-Quality", "name": "Non-Functional Quality"},
        {"code": "CAT-NON-FUNC-Constant", "name": "Non-Functional Constant"},
        {"code": "CAT-NON-FUNC-Performance", "name": "Non-Functional Performance"},
        {"code": "CAT-NON-FUNC-Security", "name": "Non-Functional Security"},
    ]
    for cat in categories:
        if not CategoryModel.objects.filter(code=cat["code"]).exists():
            CategoryModel.objects.create(project=project, **cat)

    # 10. Create User Settings
    for user in User.objects.all():
        user_setting, _ = UserSettingModel.objects.get_or_create(user=user)
        user_setting.page_size = 20
        if project and user == owner:
            user_setting.project = project
        user_setting.save()

    # 11. Create Specification Import Types
    if owner:
        import_types = [
            {"code": "Local", "name": "Local", "is_active": True},
            {"code": "Google", "name": "Google", "is_active": True},
            {"code": "GitHub", "name": "GitHub", "is_active": True},
            {"code": "Jama", "name": "Jama", "is_active": True},
        ]
        for itype in import_types:
            if not SpecificationImportTypeModel.objects.filter(
                code=itype["code"]
            ).exists():
                SpecificationImportTypeModel.objects.create(
                    created_by=owner, updated_by=owner, **itype
                )

    # 12. Create project settings
    if project:
        project_settings = [
            {
                "github_url": "",
                "jama_project_id": 368,
                "jama_url": "https://stargate.jamacloud.com/",
                "jama_swrd_item_type": 0,
                "jama_swqt_item_type": 0,
                "jama_scrd_item_type": 0,
                "jama_scqt_item_type": 0,
                "jama_sud_item_type": 0,
                "jama_sut_item_type": 0,
            }
        ]

        print(project)
        for project_setting in project_settings:
            if not ProjectSettingModel.objects.filter(project=project).exists():
                ProjectSettingModel.objects.create(project=project, **project_setting)


def remove_initial_data(apps, schema_editor):
    """Remove the initial data."""
    CategoryModel = apps.get_model("specification_centralized_core", "CategoryModel")
    ComplexityModel = apps.get_model(
        "specification_centralized_core", "ComplexityModel"
    )
    ComponentModel = apps.get_model("specification_centralized_core", "ComponentModel")
    FunctionModel = apps.get_model("specification_centralized_core", "FunctionModel")
    PriorityModel = apps.get_model("specification_centralized_core", "PriorityModel")
    ProcessModel = apps.get_model("specification_centralized_core", "ProcessModel")
    ProjectMilestoneModel = apps.get_model(
        "specification_centralized_core", "ProjectMilestoneModel"
    )
    ProjectModel = apps.get_model("specification_centralized_core", "ProjectModel")
    ProjectSettingModel = apps.get_model(
        "specification_centralized_core", "ProjectSettingModel"
    )
    UserSettingModel = apps.get_model(
        "specification_centralized_core", "UserSettingModel"
    )
    SpecificationImportTypeModel = apps.get_model(
        "specification_centralized_core", "SpecificationImportTypeModel"
    )
    User = apps.get_model("auth", "User")

    CategoryModel.objects.all().delete()
    ComplexityModel.objects.all().delete()
    ComponentModel.objects.all().delete()
    FunctionModel.objects.all().delete()
    PriorityModel.objects.all().delete()
    ProcessModel.objects.all().delete()
    ProjectMilestoneModel.objects.all().delete()
    ProjectSettingModel.objects.all().delete()
    ProjectModel.objects.all().delete()
    UserSettingModel.objects.all().delete()
    SpecificationImportTypeModel.objects.all().delete()
    User.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("specification_centralized_core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_code=remove_initial_data),
    ]
