"""
Django settings for specification_centralized_auth_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def get_gcp_secret_for_settings(secret_id: str, version_id: str = "latest") -> str:
    """Minimal GCP secret fetcher for use during settings initialization."""
    try:
        from google.cloud import secretmanager
        from google.oauth2 import service_account
        import google.auth

        project_id = os.environ.get("GOOGLE_PROJECT_ID")
        creds_path = os.environ.get("GOOGLE_CREDENTIALS_FILE")

        if not project_id:
            return None

        credentials = None
        if creds_path and os.path.exists(creds_path):
            credentials = service_account.Credentials.from_service_account_file(
                creds_path
            )
        else:
            credentials, _ = google.auth.default()

        client = secretmanager.SecretManagerServiceClient(credentials=credentials)
        name = f"projects/{project_id}/secrets/{secret_id}/versions/{version_id}"
        response = client.access_secret_version(request={"name": name})
        return response.payload.data.decode("UTF-8")
    except Exception as e:
        print(f"Warning: Failed to retrieve secret '{secret_id}' for settings: {e}")
        return None


# Load environment variables from .env file if it exists
try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None


if load_dotenv:
    env = os.environ.get("DJANGO_ENV", "dev")
    load_dotenv(BASE_DIR / f".env.{env}")

# It's better to set these directly in the environment or a .env file
# For demonstration, we fetch them if needed.
db_username = None
db_password = None

# Example of fetching DB credentials from a single JSON secret in GCP
gcp_db_creds_secret_name = os.environ.get("GOOGLE_SECRET_KEY_DB_CREDS")
if gcp_db_creds_secret_name:
    db_creds_json = get_gcp_secret_for_settings(gcp_db_creds_secret_name)
    if db_creds_json:
        db_creds = json.loads(db_creds_json)
        db_username = db_creds.get("username")
        db_password = db_creds.get("password")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# It's recommended to load the secret key from an environment variable or a secret manager.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-)87)45elyjku4c2ojr6s0a&*n%(t=cvvd$^=afk5v4+7c=tu6z",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS_STRING = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STRING.split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "specification_centralized_core",
    "specification_centralized_auth",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "specification_centralized_auth_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "specification_centralized_auth_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME"),
        "USER": db_username,
        "PASSWORD": db_password,
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
#STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_ROOT = BASE_DIR / "specification_centralized_admin_project/staticfiles"


# Configuration for the 'core' reusable app
RUN_CORE_INITIAL_DATA_MIGRATION = (
    os.environ.get("RUN_CORE_INITIAL_DATA_MIGRATION", "False") == "True"
)

GOOGLE_PROJECT_ID = os.environ.get("GOOGLE_PROJECT_ID")
GOOGLE_LOCATION = os.environ.get("GOOGLE_LOCATION")
GOOGLE_CREDENTIALS_FILE = os.environ.get("GOOGLE_CREDENTIALS_FILE")
GOOGLE_SECRET_KEY_DB_CREDS = os.environ.get("GOOGLE_SECRET_KEY_DB_CREDS")
